name: Build
on: [push]
jobs:
  build:
    env:
      GONOSUMDB: "github.com/moby/moby"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t ./...

      - name: Unit Test
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /functional_tests)
          go test -v ./pkg/shipyard

      - name: Build
        run: |
          go build -v .

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
  
  functional_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and install 
      run: make install_local
    
    - name: Run tests
      run: make test_functional