name: Go
on: [push]
jobs:
  build:
    env:
      GONOSUMDB: "*"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          GONOSUMDB="*" go get -v -t -d ./...
        env:
          GONOSUMDB: "*"

      - name: Unit Test
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic $(go list ./... | grep -v /functional_tests)
        env:
          GONOSUMDB: "*"

      - name: Build
        run: |
          go build -v .
        env:
          GONOSUMDB: "*"

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
