name: goreleaser

on:
  pull_request:
  push:
    tags:
       - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Unshallow
        run: git fetch --prune --unshallow
      
      -
        name: Docker Login
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin 
      -
        name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
          key: ${{ secrets.GPG_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
  choco:
    needs: goreleaser
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'shipyard-run/choco-package'

      - name: Tag
        id: tag
        uses: ashley-taylor/regex-property-action@v1.0
        with:
          value: ${{ github.ref }}
          regex: "v"
          replacement: "" 

      - 
        name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "__version__"
          replace: "${{ steps.tag.outputs.value }}"

      -
        name: Choco login
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: apikey -k ${{ secrets.CHOCO_API_KEY }} -s https://push.chocolatey.org/
      
      -
        name: Choco build
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: pack
      
      -
        name: Choco push
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: push